### ISSUE TITLE
Pull requests to raphaeljolivet ?

### ISSUE THREAD

**Issue by raDiesle** [kevoree-modeling/java2typescript#6]
Hi,

I see, that you have well enhanced it.
How about merging with master of raphael?

Would be great!

**Comment by dukeboard** [comment]
Hi, 

I did see any raphael in the fork network of the project. Can you give a like to it ?
Any improvement are welcome of course :-)

**Comment by raDiesle** [comment]
Hi duke, I mean to merge your form with the original one,
so that you make pull requests.
Thanks!
