### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by ramaghanta** [kevoree-modeling/java2typescript#7]
Hi,

Would you be able to add some documentation on how to setup and get this working with Maven?

Thanks

**Comment by dukeboard** [comment]
Hello, I will push you a minimal readme and sample project in the day.
Regards

**Comment by dukeboard** [comment]
Hello, I added a small readme and a sample project to download, showing both compilation configuration and result code usage in browser.

Regards,

**Comment by maxleiko** [comment]
@ramaghanta just make sure you installed `tsc` globally in order for the Maven plugin to work.

```sh
npm i -g typescript
```

**Comment by ramaghanta** [comment]
Thank You @dukeboard and @maxleiko for your help. Much appreciated.
